package BRUpos;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author never
 * Program Name: CEIS355A_Norment_Xavier_Week3Lab.java
 * Programmer's Name: Xavier Norment
 * Program Description: 
 *      this is a basic GUI style POS system for BurgersRus
 */

public class BurgersRUsPOS extends javax.swing.JFrame {
    //creating default prices
    private double singlePrice = 3.50, doublePrice = 4.75, cheesePrice = .5, 
            baconPrice = 1.25, mealPrice = 4.0, totalPrice = 0.0, orderTotalPrice = 0.0;
    /**
     * Creates new form NewJFrame
     */
    public BurgersRUsPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btngrpBurgerStyle = new javax.swing.ButtonGroup();
        lblOrder = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareaYourOrder = new javax.swing.JTextArea();
        rbtnSBurger = new javax.swing.JRadioButton();
        rbtnDBurger = new javax.swing.JRadioButton();
        cboxCheese = new javax.swing.JCheckBox();
        cboxBacon = new javax.swing.JCheckBox();
        cboxMeal = new javax.swing.JCheckBox();
        lblItemPrice = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        lblOrderTotal = new javax.swing.JLabel();
        txtOrderTotal = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JFormattedTextField();
        rbtnThisIsNotVisible = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        mitemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitemAddToOrder = new javax.swing.JMenuItem();
        mitemClearForNextItem = new javax.swing.JMenuItem();
        mitemNewOrder = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burger Barn");

        lblOrder.setText("Your Order");

        tareaYourOrder.setColumns(20);
        tareaYourOrder.setRows(5);
        tareaYourOrder.setEditable(false);
        jScrollPane2.setViewportView(tareaYourOrder);

        btngrpBurgerStyle.add(rbtnSBurger);
        rbtnSBurger.setText("Singe Burger");
        rbtnSBurger.setToolTipText("");
        rbtnSBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSBurgerActionPerformed(evt);
            }
        });

        btngrpBurgerStyle.add(rbtnDBurger);
        rbtnDBurger.setText("Double Burger");
        rbtnDBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDBurgerActionPerformed(evt);
            }
        });

        cboxCheese.setText("Add Cheese");
        cboxCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCheeseActionPerformed(evt);
            }
        });

        cboxBacon.setText("Add Bacon");
        cboxBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBaconActionPerformed(evt);
            }
        });

        cboxMeal.setText("Make it a meal");
        cboxMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMealActionPerformed(evt);
            }
        });

        lblItemPrice.setText("Item Price");

        txtItemPrice.setEditable(false);

        lblQuantity.setText("Quantity");

        lblOrderTotal.setText("Order Total");

        txtOrderTotal.setEditable(false);

        txtQuantity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQuantity.setText("1");
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });

        btngrpBurgerStyle.add(rbtnThisIsNotVisible);
        rbtnThisIsNotVisible.setSelected(true);
        rbtnThisIsNotVisible.setText("you should not be able to see this");
        rbtnThisIsNotVisible.setFocusable(false);
        rbtnThisIsNotVisible.setVisible(false);

        menuMain.setText("File");

        mitemExit.setText("Exit");
        mitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemExitActionPerformed(evt);
            }
        });
        menuMain.add(mitemExit);

        jMenuBar1.add(menuMain);

        jMenu2.setText("Order");

        mitemAddToOrder.setText("Add to Order");
        mitemAddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemAddToOrderActionPerformed(evt);
            }
        });
        jMenu2.add(mitemAddToOrder);

        mitemClearForNextItem.setText("Clear for next item");
        mitemClearForNextItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemClearForNextItemActionPerformed(evt);
            }
        });
        jMenu2.add(mitemClearForNextItem);

        mitemNewOrder.setText("New Order");
        mitemNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemNewOrderActionPerformed(evt);
            }
        });
        jMenu2.add(mitemNewOrder);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbtnDBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnSBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cboxCheese)
                            .addComponent(cboxMeal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblItemPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbtnThisIsNotVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblOrder)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOrderTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(txtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnSBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnDBurger)
                        .addGap(27, 27, 27)
                        .addComponent(cboxCheese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxBacon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxMeal))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnThisIsNotVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemPrice)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderTotal)
                    .addComponent(txtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitemExitActionPerformed

    private void mitemClearForNextItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemClearForNextItemActionPerformed
        clearGUI();
    }//GEN-LAST:event_mitemClearForNextItemActionPerformed

    private void mitemAddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemAddToOrderActionPerformed
        /*
        pulls the currently selected order
        adds the current order to the order box
        updates the order total
        clears the gui
        */
        
        String custOrder = "";
        int quantity = Integer.parseInt(txtQuantity.getText());
        if (rbtnThisIsNotVisible.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Please select either a single or double burger");
        }
        if (quantity>1){
            updateOrderTotal(totalPrice*quantity);
            if (rbtnSBurger.isSelected()){
                custOrder = String.format("%s singles", txtQuantity.getText());
            }
            else if (rbtnDBurger.isSelected()){
                custOrder = String.format("%s doubles", txtQuantity.getText());
            }
        }
        else {
            updateOrderTotal(totalPrice);
            if (rbtnSBurger.isSelected()){
                custOrder = "1 single";
            }
            else if (rbtnDBurger.isSelected()){
                custOrder = "1 double";
            }
        }
        if (cboxCheese.isSelected() && cboxBacon.isSelected()){
            custOrder = custOrder + " with cheese and bacon";
        }
        else if (cboxCheese.isSelected()){
            custOrder = custOrder + " with cheese";
        }
        else {
            custOrder = custOrder + " with bacon";
        }
        if (cboxMeal.isSelected()){
            custOrder = custOrder + ", meal";
        }
        custOrder += String.format(" at $%.2f each", totalPrice);
        clearGUI();
        tareaYourOrder.append(custOrder+"\n");
    }//GEN-LAST:event_mitemAddToOrderActionPerformed

    private void mitemNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemNewOrderActionPerformed
        //fully clears gui for a new order
        clearGUI();
        tareaYourOrder.setText("");
        txtOrderTotal.setText("");
    }//GEN-LAST:event_mitemNewOrderActionPerformed

    private void rbtnSBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSBurgerActionPerformed
        // All actions that change the price of the itme will run the display price func
        displayPrice();
    }//GEN-LAST:event_rbtnSBurgerActionPerformed

    private void rbtnDBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDBurgerActionPerformed
        displayPrice();
    }//GEN-LAST:event_rbtnDBurgerActionPerformed

    private void cboxCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCheeseActionPerformed
        displayPrice();
    }//GEN-LAST:event_cboxCheeseActionPerformed

    private void cboxBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBaconActionPerformed
        displayPrice();
    }//GEN-LAST:event_cboxBaconActionPerformed

    private void cboxMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMealActionPerformed
        displayPrice();
    }//GEN-LAST:event_cboxMealActionPerformed

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        //Runs when the user clicks off quantity to check if it is valid
        
        if (txtQuantity.getText().equals("")){
            txtQuantity.setText(String.valueOf(1));
            JOptionPane.showMessageDialog(rootPane, "Please enter a whole number for the quantity");
        }
        else if (Integer.parseInt(txtQuantity.getText())<=0){
            txtQuantity.setText(String.valueOf(1));
            JOptionPane.showMessageDialog(rootPane, "Please enter a positive whole number for the quantity");
        }
    }//GEN-LAST:event_txtQuantityFocusLost

    private void clearGUI(){
        //clears out nearly all gui inputs
        rbtnThisIsNotVisible.setSelected(true);
        cboxCheese.setSelected(false);
        cboxBacon.setSelected(false);
        cboxMeal.setSelected(false);
        txtQuantity.setText(String.valueOf(1));
        displayPrice();
    }
    private void updateOrderTotal(double priceToAdd){
        //adds the current order to the total order price then updates the display
        orderTotalPrice += priceToAdd;
        txtOrderTotal.setText(String.format("$%.2f", orderTotalPrice));
    }
    private void displayPrice(){
        //pulls all inputs and upadted item price
        priceReset();
        if (rbtnSBurger.isSelected()){totalPrice += singlePrice;}
        else if (rbtnDBurger.isSelected()){totalPrice += doublePrice;}
        if (cboxCheese.isSelected()){totalPrice += cheesePrice;}
        if (cboxBacon.isSelected()){totalPrice += baconPrice;}
        if (cboxMeal.isSelected()){totalPrice += mealPrice;}
        txtItemPrice.setText(String.format("$%.2f", totalPrice));
    }
    private void priceReset(){
        totalPrice = 0.0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgersRUsPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpBurgerStyle;
    private javax.swing.JCheckBox cboxBacon;
    private javax.swing.JCheckBox cboxCheese;
    private javax.swing.JCheckBox cboxMeal;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JMenu menuMain;
    private javax.swing.JMenuItem mitemAddToOrder;
    private javax.swing.JMenuItem mitemClearForNextItem;
    private javax.swing.JMenuItem mitemExit;
    private javax.swing.JMenuItem mitemNewOrder;
    private javax.swing.JRadioButton rbtnDBurger;
    private javax.swing.JRadioButton rbtnSBurger;
    private javax.swing.JRadioButton rbtnThisIsNotVisible;
    private javax.swing.JTextArea tareaYourOrder;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtOrderTotal;
    private javax.swing.JFormattedTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
