/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceis355a_week6project;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 * Program Name: CEIS355A_Norment_Landscaping_wk6.java
 * Programmer's Name: Xavier Norment
 * Program Description:
 *      create estimated on a landscaping project based on user input
 * 
 * ||||Debugging statements added due to customer ID not pulling or updating properly
 * Found error in Customer.java||||
 */
public class LandscapeGUI extends javax.swing.JFrame {
    DefaultListModel<Customer> model;
    private final double grassPerFt2 = 7.0;
    private final double gravelPerFt2 = 4.0;
    private final double dirtPerFt2 = 3.0;
    /**
     * Creates new form NewJFrame
     */
    public LandscapeGUI() {
        model = new DefaultListModel<Customer>();
        initComponents();
        this.setLocationRelativeTo(null);
        loadCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgrpYardType = new javax.swing.ButtonGroup();
        tabMain = new javax.swing.JTabbedPane();
        pnlWelcome = new javax.swing.JPanel();
        lblWelcomeTitle = new javax.swing.JLabel();
        rbtnGrass = new javax.swing.JRadioButton();
        rbtnGravel = new javax.swing.JRadioButton();
        rbtnDirt = new javax.swing.JRadioButton();
        lblLandscapeImage = new javax.swing.JLabel();
        lblPricesWarning = new javax.swing.JLabel();
        lblPricesWarning1 = new javax.swing.JLabel();
        btnNextPage = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        rbtnChecker = new javax.swing.JRadioButton();
        pnlInfo = new javax.swing.JPanel();
        lblInfoTitle = new javax.swing.JLabel();
        lblEnterInfo = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        lblWidth = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarOrderSummary = new javax.swing.JTextArea();
        btnSumbitOrder = new javax.swing.JButton();
        lblOrderSummary = new javax.swing.JLabel();
        pnlCustList = new javax.swing.JPanel();
        lvlCustListTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCustList = new javax.swing.JList<>();
        lblCustList = new javax.swing.JLabel();
        lblCustDet = new javax.swing.JLabel();
        btnLoadCustList = new javax.swing.JButton();
        btnDeleteCust = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tareaCustDet = new javax.swing.JTextArea();
        mbarMainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mitemExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mitemSubmitOrder = new javax.swing.JMenuItem();
        mitemReset = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Landscapes!");

        tabMain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeTitle.setText("Xavier Norment's Landscapes");

        rgrpYardType.add(rbtnGrass);
        rbtnGrass.setText("Grass         - $7/sqft");
        rbtnGrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGrassActionPerformed(evt);
            }
        });

        rgrpYardType.add(rbtnGravel);
        rbtnGravel.setText("Gravel        - $4/sqft");
        rbtnGravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGravelActionPerformed(evt);
            }
        });

        rgrpYardType.add(rbtnDirt);
        rbtnDirt.setText("Local Dirt  - $3/sqft");
        rbtnDirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDirtActionPerformed(evt);
            }
        });

        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week6project/Landscaping.jpg"))); // NOI18N

        lblPricesWarning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPricesWarning.setText("*Prices are subject to change based on availability ");

        lblPricesWarning1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPricesWarning1.setText("and if specific materials are needed");

        btnNextPage.setText("Next");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        rgrpYardType.add(rbtnChecker);
        rbtnChecker.setSelected(true);
        rbtnChecker.setText("ThisDoesNotExist");
        rbtnChecker.setFocusable(false);
        rbtnChecker.setVisible(false);

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblWelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLayout.createSequentialGroup()
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPricesWarning)
                            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblPricesWarning1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbtnDirt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnGravel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnGrass))
                            .addComponent(rbtnChecker, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLandscapeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblLandscapeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbtnChecker)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnGrass)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnGravel)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnDirt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(lblPricesWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPricesWarning1))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(btnNextPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)))
                .addGap(14, 14, 14))
        );

        tabMain.addTab("Welcome", pnlWelcome);

        lblInfoTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoTitle.setText("Xavier Norment's Landscapes");

        lblEnterInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEnterInfo.setText("Please enter your information:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name:");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddress.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Enter the length and width of your yard:");

        txtLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWidth.setText("width:");

        lblLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLength.setText("Length:");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtarOrderSummary.setColumns(20);
        txtarOrderSummary.setRows(5);
        txtarOrderSummary.setFocusable(false);
        txtarOrderSummary.setEditable(false);
        jScrollPane1.setViewportView(txtarOrderSummary);

        btnSumbitOrder.setText("Submit Order");
        btnSumbitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumbitOrderActionPerformed(evt);
            }
        });

        lblOrderSummary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOrderSummary.setText("Order Summary");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnSumbitOrder)
                .addGap(14, 14, 14))
            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInfoLayout.createSequentialGroup()
                            .addComponent(lblEnterInfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOrderSummary))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlInfoLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlInfoLayout.createSequentialGroup()
                                            .addComponent(lblAddress)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtAddress))
                                        .addComponent(jLabel5)
                                        .addGroup(pnlInfoLayout.createSequentialGroup()
                                            .addComponent(lblName)
                                            .addGap(32, 32, 32)
                                            .addComponent(txtName))))
                                .addGroup(pnlInfoLayout.createSequentialGroup()
                                    .addComponent(lblLength)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtLength))
                                .addGroup(pnlInfoLayout.createSequentialGroup()
                                    .addComponent(lblWidth)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtWidth)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)))
                    .addContainerGap()))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnSumbitOrder))
                .addContainerGap())
            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEnterInfo)
                        .addComponent(lblOrderSummary))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInfoLayout.createSequentialGroup()
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAddress)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLength)
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblWidth)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        tabMain.addTab("Information", pnlInfo);

        lvlCustListTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lvlCustListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlCustListTitle.setText("Xavier Norment's Landscapes");

        lstCustList.setModel(model);
        lstCustList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCustListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstCustList);

        lblCustList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCustList.setText("Customer List");

        lblCustDet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCustDet.setText("Customer Details");

        btnLoadCustList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoadCustList.setText("Load List");
        btnLoadCustList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCustListActionPerformed(evt);
            }
        });

        btnDeleteCust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteCust.setText("Delete Customer");
        btnDeleteCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustActionPerformed(evt);
            }
        });

        tareaCustDet.setColumns(20);
        tareaCustDet.setRows(5);
        jScrollPane4.setViewportView(tareaCustDet);

        javax.swing.GroupLayout pnlCustListLayout = new javax.swing.GroupLayout(pnlCustList);
        pnlCustList.setLayout(pnlCustListLayout);
        pnlCustListLayout.setHorizontalGroup(
            pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvlCustListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustListLayout.createSequentialGroup()
                        .addGroup(pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCustListLayout.createSequentialGroup()
                                .addComponent(lblCustDet)
                                .addGap(170, 170, 170))
                            .addComponent(jScrollPane4)))
                    .addGroup(pnlCustListLayout.createSequentialGroup()
                        .addComponent(btnLoadCustList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteCust)))
                .addContainerGap())
        );
        pnlCustListLayout.setVerticalGroup(
            pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lvlCustListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustList)
                    .addComponent(lblCustDet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnlCustListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadCustList)
                    .addComponent(btnDeleteCust))
                .addContainerGap())
        );

        tabMain.addTab("Customer List", pnlCustList);

        mnuFile.setText("File");
        mnuFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mitemExit.setText("Exit");
        mitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemExitActionPerformed(evt);
            }
        });
        mnuFile.add(mitemExit);

        mbarMainMenu.add(mnuFile);

        mnuOrder.setText("Order");
        mnuOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mitemSubmitOrder.setText("Submit Order");
        mitemSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSubmitOrderActionPerformed(evt);
            }
        });
        mnuOrder.add(mitemSubmitOrder);

        mitemReset.setText("Reset");
        mitemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemResetActionPerformed(evt);
            }
        });
        mnuOrder.add(mitemReset);

        mbarMainMenu.add(mnuOrder);

        setJMenuBar(mbarMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitemExitActionPerformed

    private void mitemSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSubmitOrderActionPerformed
        submitOrder();
    }//GEN-LAST:event_mitemSubmitOrderActionPerformed

    private void rbtnGrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGrassActionPerformed
        //set the image to the grass icon when grass is checked
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week6project/Grass.jpg")));
    }//GEN-LAST:event_rbtnGrassActionPerformed

    private void rbtnGravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGravelActionPerformed
        //set the image to the gravel icon when gravel is checked
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week6project/Gravel.jpg")));
    }//GEN-LAST:event_rbtnGravelActionPerformed

    private void rbtnDirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDirtActionPerformed
        //set the image to the dirt icon when dirt is checked
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week6project/Dirt.jpg")));
    }//GEN-LAST:event_rbtnDirtActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        //move to information tab
        if (rbtnChecker.isSelected()){
            JOptionPane.showMessageDialog(this, "Plese select an option", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        tabMain.setSelectedIndex(1);
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        // validate the inputs
        if (validateInputs( ) == false )
        return;      // end the method if validation failed

        // create the Customer object and show the information
        Customer cust = createCustomer( );
        txtarOrderSummary.setText( cust.getDetails( ) );
        //model.addElement(cust);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnSumbitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumbitOrderActionPerformed
        // TODO add your handling code here:
        submitOrder();
    }//GEN-LAST:event_btnSumbitOrderActionPerformed

    private void lstCustListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCustListValueChanged
        // TODO add your handling code here
        if (lstCustList.getSelectedValue() == null){return;}
        tareaCustDet.setText(lstCustList.getSelectedValue().getDetails());
        
    }//GEN-LAST:event_lstCustListValueChanged

    private void mitemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemResetActionPerformed
        reset();
    }//GEN-LAST:event_mitemResetActionPerformed

    private void btnLoadCustListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCustListActionPerformed
        // TODO add your handling code here:
        loadCustomers();
    }//GEN-LAST:event_btnLoadCustListActionPerformed

    private void btnDeleteCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustActionPerformed
    try{
        // get the selected object
        Customer old = lstCustList.getSelectedValue();

        // if something is selected, delete it and clear the details textarea
        if (old != null){
            DataIO data = new DataIO();
            data.delete(old.getCustomerID());   // get the name only
            //System.out.println(old.getCustomerID());
            tareaCustDet.setText("");
            loadCustomers();
            }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage(), "Database driver Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex){
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                        "DataIO Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteCustActionPerformed

    public void submitOrder() 
    {
        //TODO
        //JOptionPane.showMessageDialog(this, "Method is not complete.");
        if (validateInputs() == false){
            return; // varification failed, end
        }
        Customer cust = createCustomer();
        model.addElement(cust);
        //txtarOrderSummary.setText(cust.getDetails());
        tareaCustDet.setText(cust.getDetails());
        
        try{
            DataIO data = new DataIO();
            data.add(cust);
            loadCustomers();
            reset();
            tabMain.setSelectedIndex(2);
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage(), "Database driver Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean validateInputs()
    {
        String sName = txtName.getText();
        String sAddress = txtAddress.getText();
        String sWidth = txtWidth.getText();
        String sLength = txtLength.getText();
        
        if (sName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter a Name",
                    "Name Error", JOptionPane.ERROR_MESSAGE);
            txtName.requestFocusInWindow();
            return false;
        }

        if (sAddress.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter a Address",
                    "Address Error", JOptionPane.ERROR_MESSAGE);
            txtAddress.requestFocusInWindow();
            return false;
        }

        if (sAddress.length() <= 5)
        {
            JOptionPane.showMessageDialog(this, 
"Address isn't long enough.",
                  "Address Error", JOptionPane.ERROR_MESSAGE);
            txtAddress.requestFocusInWindow();
            return false;
        }

        if (sWidth.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter a Width",
                    "Width Error", JOptionPane.ERROR_MESSAGE);
            txtWidth.requestFocusInWindow();
            return false;
        }

        try
        {
            Double.parseDouble(sWidth);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Width must be a number",
                    "Width Error", JOptionPane.ERROR_MESSAGE);
            txtWidth.setText("");
            txtWidth.requestFocusInWindow();
            return false;
        }

        if (Double.parseDouble(sWidth) <= 0)
        {
            JOptionPane.showMessageDialog(this, 
"Width must be greater than 0",
                  "Width Error", JOptionPane.ERROR_MESSAGE);
            txtLength.setText("");
            txtLength.requestFocusInWindow();
            return false;
        }

        if (sLength.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter a Length",
                    "Length Error", JOptionPane.ERROR_MESSAGE);

            txtLength.requestFocusInWindow();
            return false;
        }

        try
        {
            Double.parseDouble(sLength);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Length must be a number",
                    "Length Error", JOptionPane.ERROR_MESSAGE);
            txtLength.setText("");
            txtLength.requestFocusInWindow();
            return false;

        }

        if (Double.parseDouble(sLength) <= 0)
        {
            JOptionPane.showMessageDialog(this, 
"Length must be must be greater than 0",
                  "Length Error", JOptionPane.ERROR_MESSAGE);
            txtLength.setText("");
            txtLength.requestFocusInWindow();
            return false;
        }
        else
        {
            // all is good so return true
            return true;
        }
    }
    private Customer createCustomer()
    {
        String name = txtName.getText();
        String address = txtAddress.getText();
        double width = Double.parseDouble(txtWidth.getText());
        double length = Double.parseDouble(txtLength.getText());
        String yardType = "";                // FIX THE TYPE
        double totalCost = 0.0;               // FIX THE PRICE
        if (rbtnGrass.isSelected()){
            yardType = "Grass";
            totalCost = grassPerFt2 * width * length;
        }
        else if (rbtnGravel.isSelected()){
            yardType = "Gravel";
            totalCost = gravelPerFt2 * width * length;
        }
        else if (rbtnDirt.isSelected()){
            yardType = "Dirt";
            totalCost = dirtPerFt2 * width * length;
        }
        else{
            JOptionPane.showMessageDialog(this, "Error, please select a ayrd type");
            totalCost = 0.0;
        }

        Customer cust = new Customer(0, name, address, yardType, length, width, totalCost);
        return cust;
    }
    private void reset(){
        //clears all radio buttons and resets the image to the initial icon
        //rgrpYardType.clearSelection();
        rbtnChecker.setSelected(true);
        tabMain.setSelectedIndex(0);
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week6project/Landscaping.jpg")));
        clearEntries();
    }
    private void clearEntries(){
        txtName.setText("");
        this.txtName.requestFocusInWindow();
        txtAddress.setText("");
        txtLength.setText("");
        txtWidth.setText("");
        txtarOrderSummary.setText("");
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandscapeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDeleteCust;
    private javax.swing.JButton btnLoadCustList;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSumbitOrder;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustDet;
    private javax.swing.JLabel lblCustList;
    private javax.swing.JLabel lblEnterInfo;
    private javax.swing.JLabel lblInfoTitle;
    private javax.swing.JLabel lblLandscapeImage;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderSummary;
    private javax.swing.JLabel lblPricesWarning;
    private javax.swing.JLabel lblPricesWarning1;
    private javax.swing.JLabel lblWelcomeTitle;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JList<Customer> lstCustList;
    private javax.swing.JLabel lvlCustListTitle;
    private javax.swing.JMenuBar mbarMainMenu;
    private javax.swing.JMenuItem mitemExit;
    private javax.swing.JMenuItem mitemReset;
    private javax.swing.JMenuItem mitemSubmitOrder;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JPanel pnlCustList;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JRadioButton rbtnChecker;
    private javax.swing.JRadioButton rbtnDirt;
    private javax.swing.JRadioButton rbtnGrass;
    private javax.swing.JRadioButton rbtnGravel;
    private javax.swing.ButtonGroup rgrpYardType;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextArea tareaCustDet;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWidth;
    private javax.swing.JTextArea txtarOrderSummary;
    // End of variables declaration//GEN-END:variables

    private void loadCustomers() {
        try{
            DataIO data = new DataIO(); // create DataIO object
            ArrayList<Customer> customers = data.getList();

            // clear out the DefaultListModel and textarea
            model.clear();
            tareaCustDet.setText("");

            // copy each object from the ArrayList over to the DefaultListModel
            for( int i = 0; i < customers.size(); i++ ){
            model.addElement(customers.get(i));
            //System.out.println(customers.get(i).getDetails());
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
            "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage(), "Database driver Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
