/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceis355a_week3project;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 */
public class LandscapeGUI_Welcome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LandscapeGUI_Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgrpYardType = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblPricesWarning = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        lblPricesWarning1 = new javax.swing.JLabel();
        rbtnGrass = new javax.swing.JRadioButton();
        rbtnGravel = new javax.swing.JRadioButton();
        rbtnDirt = new javax.swing.JRadioButton();
        lblLandscapeImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mitemExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mitemSubmitOrder = new javax.swing.JMenuItem();
        mitemReset = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Xavier Norment's Landscapes");

        lblPricesWarning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPricesWarning.setText("*Prices are subject to change based on availability ");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnNextPage.setText("Next");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        lblPricesWarning1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPricesWarning1.setText("and if specific materials are needed");

        rgrpYardType.add(rbtnGrass);
        rbtnGrass.setText("Grass         - $7/sqft");
        rbtnGrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGrassActionPerformed(evt);
            }
        });

        rgrpYardType.add(rbtnGravel);
        rbtnGravel.setText("Gravel       - $4/sqft");
        rbtnGravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGravelActionPerformed(evt);
            }
        });

        rgrpYardType.add(rbtnDirt);
        rbtnDirt.setText("Local Dirt - $3/sqft");
        rbtnDirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDirtActionPerformed(evt);
            }
        });

        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week3project/Landscaping.jpg"))); // NOI18N

        mnuFile.setText("File");

        mitemExit.setText("Exit");
        mitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemExitActionPerformed(evt);
            }
        });
        mnuFile.add(mitemExit);

        jMenuBar1.add(mnuFile);

        mnuOrder.setText("Order");

        mitemSubmitOrder.setText("Submit Order");
        mitemSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSubmitOrderActionPerformed(evt);
            }
        });
        mnuOrder.add(mitemSubmitOrder);

        mitemReset.setText("Reset");
        mitemReset.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                mitemResetAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        mnuOrder.add(mitemReset);

        jMenuBar1.add(mnuOrder);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPricesWarning, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblPricesWarning1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNextPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbtnDirt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnGravel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnGrass))
                                .addGap(102, 102, 102)
                                .addComponent(lblLandscapeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLandscapeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rbtnGrass)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnGravel)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnDirt)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPricesWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPricesWarning1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNextPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnGrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGrassActionPerformed
        //set the image to the grass icon when grass is checked
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week3project/Grass.jpg")));
    }//GEN-LAST:event_rbtnGrassActionPerformed

    private void rbtnGravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGravelActionPerformed
        //set the image to the gravel icon when gravel is checked
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week3project/Gravel.jpg")));
    }//GEN-LAST:event_rbtnGravelActionPerformed

    private void rbtnDirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDirtActionPerformed
        //set the image to the dirt icon when dirt is checked
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week3project/Dirt.jpg")));
    }//GEN-LAST:event_rbtnDirtActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        //create second GUI
        LandscapeGUI_Info infoForm = new LandscapeGUI_Info();
        //set default close operation to dispose so app stays open
        infoForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //launch second gui
        infoForm.setVisible(true);
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void mitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitemExitActionPerformed

    private void mitemSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSubmitOrderActionPerformed
        //TODO
        JOptionPane.showMessageDialog(this, "Method is not complete.");
    }//GEN-LAST:event_mitemSubmitOrderActionPerformed

    private void mitemResetAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mitemResetAncestorMoved
        reset();
    }//GEN-LAST:event_mitemResetAncestorMoved

    private void reset(){
        //clears all radio buttons and resets the image to the initial icon
        rgrpYardType.clearSelection();
        lblLandscapeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceis355a_week3project/Landscaping.jpg")));
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandscapeGUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandscapeGUI_Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnReset;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLandscapeImage;
    private javax.swing.JLabel lblPricesWarning;
    private javax.swing.JLabel lblPricesWarning1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem mitemExit;
    private javax.swing.JMenuItem mitemReset;
    private javax.swing.JMenuItem mitemSubmitOrder;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JRadioButton rbtnDirt;
    private javax.swing.JRadioButton rbtnGrass;
    private javax.swing.JRadioButton rbtnGravel;
    private javax.swing.ButtonGroup rgrpYardType;
    // End of variables declaration//GEN-END:variables
}
