package SGrades;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author never
 * Program Name: CEIS355A_Norment_Xavier_Week6Lab.java
 * Programmer's Name: Xavier Norment
 * Program Description:
 *      Will take and average grades provided in a GUI and saved in a SQL 
 *      database named week6lab within ceis355a
 */
public class SGradesGUI extends javax.swing.JFrame {

    /**
     * Creates new form SGradesGUI
     */
    public SGradesGUI() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTest1 = new javax.swing.JLabel();
        lblTest2 = new javax.swing.JLabel();
        lblTest3 = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        btnDisplayAll = new javax.swing.JButton();
        ftxtTest1 = new javax.swing.JFormattedTextField();
        ftxtTest2 = new javax.swing.JFormattedTextField();
        ftxtTest3 = new javax.swing.JFormattedTextField();
        scrStudents = new javax.swing.JScrollPane();
        tareaStudents = new javax.swing.JTextArea();
        scrStudentsTable = new javax.swing.JScrollPane();
        tblStudentsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grades");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTest1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTest1.setText("Test 1");

        lblTest2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTest2.setText("Test 2");

        lblTest3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTest3.setText("Test 3");

        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnDisplayAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDisplayAll.setText("Display All");
        btnDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllActionPerformed(evt);
            }
        });

        ftxtTest1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtTest1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ftxtTest2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtTest2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ftxtTest3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtTest3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tareaStudents.setColumns(20);
        tareaStudents.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        tareaStudents.setRows(5);
        tareaStudents.setFocusable(false);
        scrStudents.setViewportView(tareaStudents);

        tblStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrStudentsTable.setViewportView(tblStudentsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrStudentsTable)
                    .addComponent(scrStudents, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTest3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftxtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDisplayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ftxtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ftxtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest1)
                    .addComponent(ftxtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTest2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTest3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrStudentsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        String sName = txtName.getText();
        double test1 = Double.parseDouble(ftxtTest1.getText());
        double test2 = Double.parseDouble(ftxtTest2.getText());
        double test3 = Double.parseDouble(ftxtTest3.getText());
        
        Student stu = new Student(sName, test1, test2, test3);
        
        StudentDB db = new StudentDB();
        try{
            db.add(stu);
            JOptionPane.showMessageDialog(this, "Record written to database");
            clearForm();
        }
        catch (ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Error, database driver not found", "Driver not found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error, unable to add to SQL db", "SQL error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(SGradesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        // TODO add your handling code here:
        //text area
        tareaStudents.setText(String.format("%-20s", "Name")+"\tTest1\tTest2\tTetst3\tAverage\tGrade\n");
        
        StudentDB db = new StudentDB();
        try {
            ArrayList<Student> data = db.getAll();
            DecimalFormat fmt = new DecimalFormat("0.0");
            for (int i=0;i<data.size();i++){
                Student stu = data.get(i);
                tareaStudents.append(String.format("%-20s", stu.getName())+"\t"+stu.getTest1()+"\t"+
                        stu.getTest2()+"\t"+stu.getTest3()+"\t"+
                        fmt.format(stu.getAverage())+"\t"+stu.getLetterGrade()+"\n");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error, database driver not found", "Driver not found", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(SGradesGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error, unable to pull from SQL db", "SQL error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(SGradesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //table
        DefaultTableModel tblModel = new DefaultTableModel();
        String[] colTitles = {"Name", "Test1", "Test2", "Test3", "Average", "Grade"};
        tblStudentsTable.setModel(tblModel);
        tblModel.setColumnIdentifiers(colTitles);
        
        StudentDB db2 = new StudentDB();
        try {
            ArrayList<Student> records = db2.getAll();
            DecimalFormat fmt2 = new DecimalFormat("0.0");
            for (int i=0;i<records.size();i++){
                Student stu = records.get(i);
                
                Object[] row = {stu.getName(), stu.getTest1(), stu.getTest1(),
                    stu.getTest3(), fmt2.format(stu.getAverage()), stu.getLetterGrade()};
                tblModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error, database driver not found", "Driver not found", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(SGradesGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error, unable to pull from SQL db", "SQL error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(SGradesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDisplayAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SGradesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SGradesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SGradesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SGradesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SGradesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JFormattedTextField ftxtTest1;
    private javax.swing.JFormattedTextField ftxtTest2;
    private javax.swing.JFormattedTextField ftxtTest3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JScrollPane scrStudents;
    private javax.swing.JScrollPane scrStudentsTable;
    private javax.swing.JTextArea tareaStudents;
    private javax.swing.JTable tblStudentsTable;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        txtName.setText("");
        ftxtTest1.setText("");
        ftxtTest2.setText("");
        ftxtTest3.setText("");
        txtName.requestFocus();
    }
}
