/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceis355a_lab;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 * Program Name: CEIS355A_Norment_Xavier_Week2Lab.java
 * Programmer's Name: Xavier Norment
 * Program Description:
 *      Grab input from users and return their BMI using a GUI
 */
 
public class HealthProfileGUI extends javax.swing.JFrame {
    HealthProfile hp = new HealthProfile();
    /**
     * Creates new form NewJFrame
     */
    public HealthProfileGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHeightFt = new javax.swing.JLabel();
        lblHeightIn = new javax.swing.JLabel();
        lblBmi = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        lblMaxHeartRate = new javax.swing.JLabel();
        txtBmi = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtMaxHR = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        ftxtAge = new javax.swing.JFormattedTextField();
        ftxtWeight = new javax.swing.JFormattedTextField();
        ftxtHeightFt = new javax.swing.JFormattedTextField();
        ftxtHeightIn = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Health Profile");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setText("Name");

        lblAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAge.setText("Age");

        lblWeight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWeight.setText("Weight");

        lblHeightFt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHeightFt.setText("Height - Feet");

        lblHeightIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHeightIn.setText("Height - Inches");

        lblBmi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBmi.setText("BMI");

        btnDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisplayMouseClicked(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCategory.setText("Category");

        lblMaxHeartRate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaxHeartRate.setText("Max Heart Rate");

        txtBmi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBmi.setEditable(false);

        txtCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCategory.setEditable(false);

        txtMaxHR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaxHR.setEditable(false);

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        ftxtAge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ftxtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtAgeFocusLost(evt);
            }
        });

        ftxtWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtWeight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ftxtWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtWeightFocusLost(evt);
            }
        });

        ftxtHeightFt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtHeightFt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ftxtHeightFt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtHeightFtFocusLost(evt);
            }
        });

        ftxtHeightIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtHeightIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ftxtHeightIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtHeightInFocusLost(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeightFt)
                            .addComponent(lblBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategory)
                            .addComponent(lblMaxHeartRate)
                            .addComponent(lblHeightIn)
                            .addComponent(lblWeight)
                            .addComponent(lblName))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaxHR)
                    .addComponent(txtCategory)
                    .addComponent(txtBmi)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(ftxtAge)
                    .addComponent(ftxtWeight)
                    .addComponent(ftxtHeightFt)
                    .addComponent(ftxtHeightIn)
                    .addComponent(txtName))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(ftxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(ftxtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeightFt)
                    .addComponent(ftxtHeightFt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeightIn)
                    .addComponent(ftxtHeightIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBmi)
                    .addComponent(txtBmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxHeartRate)
                    .addComponent(txtMaxHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayMouseClicked
        // TODO add your handling code here:
        hp.setName(txtName.getText());
        hp.setAge(Integer.parseInt(ftxtAge.getText()));
        hp.setHeight(Integer.parseInt(ftxtHeightFt.getText()),Integer.parseInt(ftxtHeightIn.getText()));
        hp.setWeight(Integer.parseInt(ftxtWeight.getText()));
        txtBmi.setText(String.format("%.1f",hp.getBMI()));
        txtCategory.setText(String.valueOf(hp.getCategory()));
        txtMaxHR.setText(String.valueOf(hp.getMaxHR()));
        
    }//GEN-LAST:event_btnDisplayMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtName.setText("");
        ftxtAge.setText("");
        ftxtWeight.setText("");
        ftxtHeightFt.setText("");
        ftxtHeightIn.setText("");
        txtBmi.setText("");
        txtCategory.setText("");
        txtMaxHR.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void ftxtHeightInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtHeightInFocusLost
        // TODO add your handling code here:
        InputChecker(ftxtHeightIn.getText());
    }//GEN-LAST:event_ftxtHeightInFocusLost

    private void ftxtHeightFtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtHeightFtFocusLost
        // TODO add your handling code here:
        InputChecker(ftxtHeightFt.getText());
    }//GEN-LAST:event_ftxtHeightFtFocusLost

    private void ftxtWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtWeightFocusLost
        // TODO add your handling code here:
        InputChecker(ftxtWeight.getText());
    }//GEN-LAST:event_ftxtWeightFocusLost

    private void ftxtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtAgeFocusLost
        // TODO add your handling code here:
        InputChecker(ftxtAge.getText());
    }//GEN-LAST:event_ftxtAgeFocusLost
    private void InputChecker(String pullFromInput){
        try{
            
            Double.parseDouble(pullFromInput);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Invalid entry, please enter a number");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthProfileGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JFormattedTextField ftxtAge;
    private javax.swing.JFormattedTextField ftxtHeightFt;
    private javax.swing.JFormattedTextField ftxtHeightIn;
    private javax.swing.JFormattedTextField ftxtWeight;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBmi;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblHeightFt;
    private javax.swing.JLabel lblHeightIn;
    private javax.swing.JLabel lblMaxHeartRate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBmi;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtMaxHR;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
